# Generated by Django 4.2.6 on 2023-11-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Enter your full name', max_length=50),
        ),
    ]
