# Generated by Django 4.2.6 on 2023-11-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
