# Generated by Django 4.2.6 on 2023-11-07 00:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='product_images/noimage.webp', force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='product_images/'),
        ),
    ]
