# Generated by Django 4.2.6 on 2023-11-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_added_date_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4_url',
        ),
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
